# build environment
FROM node:lts-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ["package.json","yarn.lock","./"]

RUN rm -rf node_modules && yarn install --frozen-lockfile

# RUN yarn add react-scripts -g

COPY . ./

RUN yarn build


## production environment
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
