version: "3.9"
services:
  webapp:
    container_name: rcg
    build:
      context: .
      dockerfile: Dockerfile
    image: rcg
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3000
